Turkish Update 4.2.2
TrianguloY/OpenInWhatsapp_Translation pull request #51
Opened 2023-04-27 07:55 UTC by HuseyinFiliz

Based on my earlier message, I would like to inform you that I have made the necessary corrections to the translation, including the minor errors and the oversight in not including the contributions of the other Turkish translator. The updated request will be submitted promptly once the corrections have been thoroughly reviewed.

2023-04-27 08:22 UTC, TrianguloY commented
Perfect, thank you for the translation update! 

I'll review and merge it on the next days, feel free to update it if necessary (or create new prs if you discover a problem after merging)

2023-04-27 09:41 UTC, HuseyinFiliz commented
I dont plan to make any further changes until the update is released, unless a new addition is made in the original language that requires a translation update or until the update is featured in the Play Store's 'What's New' seçtin (changelog). Would joining the beta program enable me to receive the update faster? Also, is there a way to download the update as an APK file instead of waiting for it to become available on the Play Store? Furthermore, could you provide me with a code to test the donation version?

2023-04-27 10:14 UTC, TrianguloY commented
> Would joining the beta program enable me to receive the update faster? 

Yes, I always test new version as beta first (they rarely fail but just in case)

> Also, is there a way to download the update as an APK file instead of waiting for it to become available on the Play Store? 

Nothing automated, but I can build it and post it here if you want.

> Furthermore, could you provide me with a code to test the donation version?

Sure! Send me an email to send it to you there.

2023-04-27 10:29 UTC, HuseyinFiliz commented
If you can share the update here before it's released on the Play Store, I can test it for you at the same time. That would be great for me too. Thank you for your interest, I have sent an email.

2023-04-27 20:41 UTC, TrianguloY commented
[app-original-evaluation.zip](https://github.com/TrianguloY/OpenInWhatsapp_Translation/files/11347664/app-original-evaluation.zip)

Note: this is an unsigned debug version that can be installed without removing the original from play store (it's considered a different app). It may fail, and anyone could theoretically create updates for it (which may be dangerous if you install an update from somewhere else), so use it to test the update and then I suggest to uninstall it.
There are no changes other than the ones from this pr.

2023-04-28 05:03 UTC, HuseyinFiliz commented
Wow, I didn't expect it to turn out this well. I was a bit apprehensive about making mistakes since this was my first translation, but when I checked it in the application, everything looked perfect. Thank you for the prompt feedback.

Note: I didn't have to remove the previous application, so it is still installed. Now there are two different applications :)

2023-04-28 06:59 UTC, TrianguloY commented
Perfect, I'll merge it tonight (or tomorrow I hope).

As for the two apps, yes, perhaps my comment wasn't well written. It is considered a different application, that's why you didn't need to uninstall the play store one. 
This version however isn't signed so anyone could create malicious updates for it. Just don't install random apks from other sources and you are good, but still I recommend to uninstall it when you finish reviewing it (it will become obsolete once the normal app is updated in any case).

2023-04-28 18:31 UTC, TrianguloY requested changes

2023-04-28 18:31 UTC, TrianguloY commented on PlayStore/tr-TR.xml
> +    <description_short max_chars="80">Rehbere kaydetmeden bir numarayla WhatsApp'tan konuşmanızı sağlayan küçük ve reklamsız bir uygulama.</description_short>
This description_short is longer than 80 characters. Can you reduce it? It can't be updated if longer.

2023-04-28 19:52 UTC, HuseyinFiliz commented
Can you make the change?

<description_short max_chars="80">Rehbere kaydetmeden WhatsApp'tan konuşmanızı sağlar. Küçük ve reklamsız.</description_short>

2023-04-28 19:57 UTC, merged

2023-04-29 16:00 UTC, TrianguloY commented
@HuseyinFiliz I sent you the code by email yesterday, did you not receive it? 
I've sent it again now.

2023-04-29 17:41 UTC, HuseyinFiliz commented
It went to my email spam folder. Thank you.

2023-04-29 18:46 UTC, TrianguloY commented
> It went to my email spam folder. Thank you.

Oh, I don't like that my emails are considered spam (I rarely send them), maybe because of the code? If you can mark it as no-spam that would help, I guess.

2023-04-29 18:54 UTC, HuseyinFiliz commented
I have marked it as not spam. Thank you for the code :)